"""
Django settings for wallbox_project project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'charging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow same-origin iframes so the Reports page can embed its own PDFs.
# Django's default is "DENY" which silently breaks the inline PDF viewer
# even though the PDF response is served from this same Django process.
X_FRAME_OPTIONS = "SAMEORIGIN"

ROOT_URLCONF = 'wallbox_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wallbox_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# KEBA P30 wallbox — HTTP CSV export via the web GUI (replays browser login).
KEBA_HOST = env("KEBA_HOST", default="")
KEBA_USERNAME = env("KEBA_USERNAME", default="")
KEBA_PASSWORD = env("KEBA_PASSWORD", default="")
# Diagnostic tee: if set, every fetched CSV body is written here before parse.
KEBA_DUMP_DIR = env("KEBA_DUMP_DIR", default="")

# KEBA REST API (Phase 2.6+) — consumed by KebaApiClient.
# Defaults are intentionally lazy; the client validates at instantiation.
KEBA_API_URL = env("KEBA_API_URL", default="")
KEBA_API_VERIFY_TLS = env.bool("KEBA_API_VERIFY_TLS", default=False)
KEBA_API_USERNAME = env("KEBA_API_USERNAME", default="")
KEBA_API_PASSWORD = env("KEBA_API_PASSWORD", default="")

# Email (Phase 3) — SMTP transport for the monthly report. Empty EMAIL_HOST
# falls back to Django's console backend so unit tests and CLI runs without
# a configured server are still safe; the dispatcher checks EMAIL_HOST
# explicitly before sending so missing config surfaces as a clear UI error
# instead of silently writing to stdout.
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if env("EMAIL_HOST", default="")
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="wallbox@localhost")

# Reporter and vehicle profile — printed on every monthly PDF report.
# Required: missing values raise ImproperlyConfigured at startup so we never
# silently render a blank field in the PDF.
REPORTER_NAME = env("REPORTER_NAME")
REPORTER_EMPLOYEE_ID = env("REPORTER_EMPLOYEE_ID")
VEHICLE_MAKE_MODEL = env("VEHICLE_MAKE_MODEL")
VEHICLE_LICENSE_PLATE = env("VEHICLE_LICENSE_PLATE")
CHARGING_LOCATION = env("CHARGING_LOCATION")
