# Generated by Django 5.2.14 on 2026-05-08 20:48

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('pdf', models.FileField(blank=True, upload_to=reports.models.report_pdf_path)),
                ('send_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='monthlyreport_year_month_unique'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthlyreport_month_range')],
            },
        ),
    ]
