# Generated by Django 5.2.14 on 2026-05-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_price_ct_per_kwh', models.DecimalField(decimal_places=3, max_digits=6)),
                ('base_fee_eur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valid_from', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
