# Generated by Django 5.2.14 on 2026-05-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('kwh', models.DecimalField(decimal_places=3, max_digits=8)),
                ('meter_start', models.DecimalField(decimal_places=3, max_digits=12)),
                ('meter_end', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__isnull', True), ('end__gte', models.F('start')), _connector='OR'), name='chargingsession_end_after_start'), models.CheckConstraint(condition=models.Q(('meter_end__isnull', True), ('meter_end__gte', models.F('meter_start')), _connector='OR'), name='chargingsession_meter_end_after_start')],
            },
        ),
    ]
