# Generated by Django 5.2.14 on 2026-05-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0002_replace_with_csv_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(db_index=True, unique=True)),
                ('energy_price_ct_per_kwh', models.DecimalField(decimal_places=3, max_digits=6)),
                ('base_fee_eur_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
