# Generated by Django 5.2.14 on 2026-05-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0002_chargingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHouseUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('household_kwh', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='monthlyhouseusage_year_month_unique'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='monthlyhouseusage_month_range')],
            },
        ),
    ]
