# Generated by Django 5.2.14 on 2026-05-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_monthlyhouseusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='ocpp_transaction_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
