# Generated by Django 5.2.14 on 2026-05-09 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHouseUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('meter_start_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('meter_end_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('kwh_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_house_usage_per_month')],
            },
        ),
    ]
