# Generated by Django 5.2.14 on 2026-05-09 20:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0004_monthlyhouseusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('pdf', models.FileField(blank=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallbox_kwh_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('energy_cost_eur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('house_kwh_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('prorated_base_fee_eur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount_eur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('warning_house_usage_missing', models.BooleanField(default=False)),
                ('tariff_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='charging.tariff')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_monthly_report')],
            },
        ),
    ]
