# Generated by Django 5.2.14 on 2026-05-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0005_monthlyreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyHouseUsage',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='house_kwh_total',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='prorated_base_fee_eur',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='warning_house_usage_missing',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='base_fee_eur_per_month',
        ),
    ]
