# Generated by Django 5.2.14 on 2026-05-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0006_delete_monthlyhouseusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='mva_record_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='mva_record_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
