# Generated by Django 5.2.14 on 2026-05-15 22:09

import charging.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0007_mva'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keba_api_username', models.CharField(blank=True, default='', max_length=64)),
                ('keba_api_password', charging.fields.EncryptedField(blank=True, default='')),
                ('report_recipient_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
    ]
