# Generated by Django 5.2.14 on 2026-05-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0008_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='last_import_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
