# Generated by Django 5.2.14 on 2026-05-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0009_appsettings_last_import_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(db_index=True, unique=True)),
                ('pdf', models.FileField(upload_to='tariff_documents/')),
                ('provider_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
